auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “hope0922's Blog”
title: “hope0922's blog
description: Everything about “hope0922.
url: http://“hope0922.github.io
feed: /atom.xml
author_info: <a href="http://“hope0922.github.io/">“hope0922</a>
