auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “Mukosame's Blog”
title: Mukosame's blog
description: Everything about Mukosame.
url: http://mukosame.github.io
feed: /atom.xml
author_info: <a href="http://mukosame.github.io/">Mukosame</a>
